### PR TITLE
updated contact list ui #56

### PR DESCRIPTION
**Pull request by chandra-pro**
Updated the Contact List UI using dummy data.

You can see the changes here.

https://github.com/glific/mobile/assets/75677045/ed0ca1e0-e5c1-499b-9ab0-45a3f4439f93

### CODE REVIEW

**Comment by mdshamoon** [comment]
@chandra-pro can you use real data coming from the backend. Update the contacts query in Contact.ts file as follows

```
export const GET_CONTACTS = gql`
  query search($filter: SearchFilter!, $contactOpts: Opts!, $messageOpts: Opts!) {
    search(filter: $filter, contactOpts: $contactOpts, messageOpts: $messageOpts) {
      contact {
        id
        name
        maskedPhone
        lastMessageAt  -> Time of the last message of the contact
      }
      message{
      id
      body -> this will be the messages for the contact. Show only the last one
     ]

    }
  }
`;
```

**Comment by chandra-pro** [comment]
Can you resolve my issue that I was getting from first day ApolloError:
Network request failed.
Without that how can I proceed to integrate backend with frontend.
If I didn't get this issue I would have resolve many issues in the glific
project

**Comment by ajaman190** [comment]
> contact {
>         id
>         name
>         maskedPhone
>         lastMessageAt  -> Time of the last message of the contact
>       }
>       message{
>       id
>       body -> this will be the messages for the contact. Show only the last one
>      ]

Hey @chandra-pro ,
1. Ensure that you have renamed the BACKEND_URL to API_BASE_URL in .env file.
2. Replaces the query with 
```sh
export const GET_CONTACTS = gql`
  query search($filter: SearchFilter!, $contactOpts: Opts!, $messageOpts: Opts!) {
    search(filter: $filter, contactOpts: $contactOpts, messageOpts: $messageOpts) {
      contact {
        id
        name
        maskedPhone
        lastMessageAt
      }
      messages {
      id
      body
     }
    }
  }
`;
```

**Comment by mdshamoon** [comment]
Closed in favor of #74

**Pull request closed without merging**
