### PR TITLE
Login UI 

### LINKED ISSUE #21: Update the UI for login screen according to the designs
**Is your feature request related to a problem? Please describe.**
Update the UI for login according to the designs

**Describe the solution you'd like**
Design file link: https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=195-2043&t=cvh8szwAja7S8PIA-0

### PR DESCRIPTION
**Pull request by ArkaPrabhaChowdhury**
Resolved #21. Login page now reflects Figma designs.

https://github.com/glific/mobile/assets/92904175/40cd9b5e-fd6e-426d-a825-940357f6cb16

### CODE REVIEW

**Comment by ArkaPrabhaChowdhury** [comment]
@mdshamoon Hey, please do check it out.

**Comment by ArkaPrabhaChowdhury** [comment]
@mdshamoon Hey, can you please check it now? I have altered the test files and the ts types.

**Review by mdshamoon — APPROVED** [review]
Looks good. I have made some more changes over your branch [here](https://github.com/glific/mobile/pull/45). Closing this PR.

**Comment by ArkaPrabhaChowdhury** [comment]
@mdshamoon I would be delighted to work on more issues. Please assign any available issues to me.

**Pull request closed without merging**
