### PR TITLE
Setup react-native-dotenv and updated the project setup instructions on Readme

### LINKED ISSUE #4: Add env file for local, staging and production environments
**Is your feature request related to a problem? Please describe.**
Some environment configurations will be different for local and production. We need to add an environment configuration file.

**Describe the solution you'd like**
The configuration file will have the variable BACKEND_URL that will be different for different environments. Also update the steps in Readme to include this.

**Additional context**
Use this package to add env file https://github.com/goatandsheep/react-native-dotenv

### PR DESCRIPTION
**Pull request by praneeth-rdy**
## Description
This pull request uses [react-native-dotenv](https://github.com/goatandsheep/react-native-dotenv) to inject the environment variables into the Javascript environment.

## Changes Made
- Added [react-native-dotenv](https://github.com/goatandsheep/react-native-dotenv) package
- Created a `.babelrc` file and configured the plugin
- Updated the readme to include the `.env` setup and usage

## Related Issues
- fixes #4

### CODE REVIEW

**Comment by praneeth-rdy** [comment]
@mdshamoon Please review the PR and lemme know if anything needs to be changed.

**Review by mdshamoon — CHANGES_REQUESTED** [review]
Looks good overall. Just add a file `.env.example` with a BACKEND_URL variable and update the steps in the readme to copy the .env.example to .env

**Comment by praneeth-rdy** [comment]
Thanks for the suggestions, @mdshamoon. I've made the changes. Please have a look.

**Review by mdshamoon — CHANGES_REQUESTED** [review]
@praneeth-rdy I think we don't need the babelrc file. We already have a babel.config. Please check if we can use that

**Review by mdshamoon — APPROVED** [review]

**Pull request merged**
