### PR TITLE
Add Conversation Filter, Modified Chat, Collection, Notification and Saved Search screen and their components, Added tests

### PR DESCRIPTION
**Pull request by ajaman190**
https://github.com/glific/mobile/assets/84832565/623f5199-2b0f-494c-bdaf-6c239f9f4162

### CODE REVIEW

**Comment by ajaman190** [comment]
@mdshamoon, I am working on the test cases. Currently, I have reached 52%, but after fixing all the failing test cases, the coverage is expected to increase.
image

**Comment by ajaman190** [comment]
Hey @VishalZ123 , have you finished reviewing this PR?

**Review by VishalZ123 — COMMENTED** [review]
@ajaman190  I have reviewed, look into it
Try to remove console logs before committing. 
LGTM
@mdshamoon Kindly review the last two commits, those are relates to jest tests.

**Comment by ajaman190** [comment]
@mdshamoon, I have resolved Vishal's requested changes. Could you please review it once for final approval and merge it? This will ensure that everyone can continue working with the latest code, as it contains significant file changes.

**Review by mdshamoon — APPROVED** [review]

**Pull request merged**
