### PR TITLE
Added contact messages page

### PR DESCRIPTION
**Pull request by chandra-pro**

### CODE REVIEW

**Comment by chandra-pro** [comment]
@mdshamoon please review the new pull request and let me know

**Comment by chandra-pro** [comment]
@mdshamoon Is there still an error in the chat_page branch as i remove all the conflicts?

**Comment by chandra-pro** [comment]
#26 Add a contact messages page issue resolved.

https://github.com/glific/mobile/assets/75677045/59819508-c864-4fcf-a6c8-6f91ba5179fc

**Review by mdshamoon — CHANGES_REQUESTED** [review]
1. Please check the formatting. Use prettier to format all the files. You can use this command 
`npx prettier --write "{src/**/*.tsx,!(node*)**/*.{js,ts,tsx}}"` or download the prettier extension

2. Let's not implement the emoji functionality and instead use a library for this.

**Comment by mdshamoon** [comment]
Closing in favor of #35

**Pull request closed without merging**
